spring:

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.10.9:5432/jvue
    username:
    password:

  cache:
    type: hazelcast

logging:
  path: /data/jvue/logs

  # hazelcast.spring.cache.prop
